/*
 * Global Search
 *
 * Search for resources with the global and shared resource properties repository integrated in the IBM Cloud platform. The search repository stores and searches cloud resources attributes, which categorize or classify resources. A resource is a physical or logical component that can be created or reserved for an application or service instance and is owned by resource providers, such as Cloud Foundry, IBM Kubernetes Service, or resource controller in IBM Cloud. Resources are uniquely identified by a Cloud Resource Name (CRN)  or by an IMS ID. The properties of a resource include tags and system properties. Both properties are defined in an IBM Cloud billing account, and span across many regions.
 *
 * API version: 2.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SupportedTypesList A list of all GhoST indices.
type SupportedTypesList struct {
	// A list of all GhoST indices.
	SupportedTypes *[]string `json:"supported_types,omitempty"`
}

// NewSupportedTypesList instantiates a new SupportedTypesList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedTypesList() *SupportedTypesList {
	this := SupportedTypesList{}
	return &this
}

// NewSupportedTypesListWithDefaults instantiates a new SupportedTypesList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedTypesListWithDefaults() *SupportedTypesList {
	this := SupportedTypesList{}
	return &this
}

// GetSupportedTypes returns the SupportedTypes field value if set, zero value otherwise.
func (o *SupportedTypesList) GetSupportedTypes() []string {
	if o == nil || o.SupportedTypes == nil {
		var ret []string
		return ret
	}
	return *o.SupportedTypes
}

// GetSupportedTypesOk returns a tuple with the SupportedTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedTypesList) GetSupportedTypesOk() (*[]string, bool) {
	if o == nil || o.SupportedTypes == nil {
		return nil, false
	}
	return o.SupportedTypes, true
}

// HasSupportedTypes returns a boolean if a field has been set.
func (o *SupportedTypesList) HasSupportedTypes() bool {
	if o != nil && o.SupportedTypes != nil {
		return true
	}

	return false
}

// SetSupportedTypes gets a reference to the given []string and assigns it to the SupportedTypes field.
func (o *SupportedTypesList) SetSupportedTypes(v []string) {
	o.SupportedTypes = &v
}

func (o SupportedTypesList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SupportedTypes != nil {
		toSerialize["supported_types"] = o.SupportedTypes
	}
	return json.Marshal(toSerialize)
}

type NullableSupportedTypesList struct {
	value *SupportedTypesList
	isSet bool
}

func (v NullableSupportedTypesList) Get() *SupportedTypesList {
	return v.value
}

func (v *NullableSupportedTypesList) Set(val *SupportedTypesList) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedTypesList) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedTypesList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedTypesList(val *SupportedTypesList) *NullableSupportedTypesList {
	return &NullableSupportedTypesList{value: val, isSet: true}
}

func (v NullableSupportedTypesList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedTypesList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


