/*
 * Global Search
 *
 * Search for resources with the global and shared resource properties repository integrated in the IBM Cloud platform. The search repository stores and searches cloud resources attributes, which categorize or classify resources. A resource is a physical or logical component that can be created or reserved for an application or service instance and is owned by resource providers, such as Cloud Foundry, IBM Kubernetes Service, or resource controller in IBM Cloud. Resources are uniquely identified by a Cloud Resource Name (CRN)  or by an IMS ID. The properties of a resource include tags and system properties. Both properties are defined in an IBM Cloud billing account, and span across many regions.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Error encountered in processing in the request
type ModelError struct {
	// A code that identifies the error.
	Code string `json:"code,omitempty"`
	// A description of the solution to the error.
	Description string `json:"description,omitempty"`
	// The severity level of the error.
	Level string `json:"level,omitempty"`
	// A description of the error detected in the request.
	Message string `json:"message,omitempty"`
	// The location of additional information about the error.
	MoreInfo string `json:"more_info,omitempty"`
	// The response received for the request.
	Response string `json:"response,omitempty"`
}
